disable upload handler because src/github.com/lizdeika/picfit/application/handlers.go:55: cannot use multipartForm (type *MultipartForm) as type binding.FieldMapper in argument to binding.Bind: 	*MultipartForm does not implement binding.FieldMapper (wrong type for FieldMap method) 		have FieldMap() binding.FieldMap 		want FieldMap(*"net/http".Request) binding.FieldMap